"""initial migration

Revision ID: d7e9240131bb
Revises: 
Create Date: 2024-12-04 08:17:44.143929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7e9240131bb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bet_id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'FINISHED_WIN', 'FINISHED_LOSE', name='betstate'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bets_bet_id'), 'bets', ['bet_id'], unique=True)
    op.create_index(op.f('ix_bets_event_id'), 'bets', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bets_event_id'), table_name='bets')
    op.drop_index(op.f('ix_bets_bet_id'), table_name='bets')
    op.drop_table('bets')
    # ### end Alembic commands ###
